# Build runtime image.
# FROM openjdk:8-jre-alpine
# COPY grpc-interop-testing/ /app/
# CMD "bin/xds-test-client --server=xds:///{server_uri} --stats_port={stats_port} --qps={qps} {rpcs_to_send} {metadata_to_send}"

FROM grpc/java-example-hostname:1.27.0

