apiVersion: v1
kind: Namespace
metadata:
  name: sergii-psm-test
  labels:
    name: sergii-psm-test

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: td-grpc-bootstrap
  namespace: sergii-psm-test
data:
  secure-server.json: |
    {
      "node": {
        "id": "projects/830293263384/networks/default-vpc/nodes/secure-server-1",
        "locality": {
          "zone": "us-central1-a",
          "region": "region",
          "sub_zone": "sub_zone"
        },
        "metadata": {
          "TRAFFICDIRECTOR_GRPC_HOSTNAME": "",
          "TRAFFICDIRECTOR_NETWORK_NAME": "default-vpc",
          "TRAFFICDIRECTOR_GCP_PROJECT_NUMBER": "830293263384",
          "version": "production"
        }
      },
      "xds_servers": [
        {
          "server_uri": "trafficdirector.googleapis.com:443",
          "channel_creds": [
            { "type": "google_default" }
          ],
          "server_features": [
            "xds_v3"
          ]
        }
      ],
      "certificate_providers": {
        "google_cloud_private_spiffe": {
          "plugin_name": "file_watcher",
          "config": {
            "certificate_file": "/var/run/gke-spiffe/certs/certificates.pem",
            "private_key_file": "/var/run/gke-spiffe/certs/private_key.pem",
            "ca_certificate_file": "/var/run/gke-spiffe/certs/ca_certificates.pem",
            "refresh_interval": "60s"
          }
        }
      }
    }
  secure-client.json: |
    {
      "node": {
        "id": "projects/830293263384/networks/default-vpc/nodes/secure-client-1",
        "locality": {
          "zone": "us-central1-a",
          "region": "region",
          "sub_zone": "sub_zone"
        },
        "metadata": {
          "TRAFFICDIRECTOR_GRPC_HOSTNAME": "",
          "TRAFFICDIRECTOR_NETWORK_NAME": "default-vpc",
          "TRAFFICDIRECTOR_GCP_PROJECT_NUMBER": "830293263384",
          "version": "production"
        }
      },
      "xds_servers": [
        {
          "server_uri": "trafficdirector.googleapis.com:443",
          "channel_creds": [
            { "type": "google_default" }
          ],
          "server_features": [
            "xds_v3"
          ]
        }
      ],
      "certificate_providers": {
        "google_cloud_private_spiffe": {
          "plugin_name": "file_watcher",
          "config": {
            "certificate_file": "/var/run/gke-spiffe/certs/certificates.pem",
            "private_key_file": "/var/run/gke-spiffe/certs/private_key.pem",
            "ca_certificate_file": "/var/run/gke-spiffe/certs/ca_certificates.pem",
            "refresh_interval": "60s"
          }
        }
      }
    }
