apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${deployment_name}
  namespace: ${namespace_name}
  labels:
    app: ${deployment_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${deployment_name}
  template:
    metadata:
      labels:
        app: ${deployment_name}
    spec:
      serviceAccountName: ${service_account_name}
      containers:
      - name: ${deployment_name}
        image: gcr.io/grpc-testing/xds-gke-interop-client-java-sergii-test:latest
        imagePullPolicy: Always
        args:
          - "--server=${server_address}"
          - "--stats_port=${stats_port}"
          - "--secure_mode=${secure_mode}"
          - "--qps=${qps}"
          - "--rpc=${rpc}"
          - "--print_response=true"
        ports:
          - containerPort: ${stats_port}
        env:
          - name: GRPC_XDS_BOOTSTRAP
            value: "/tmp/grpc-xds/td-grpc-bootstrap.json"
          - name: GRPC_XDS_EXPERIMENTAL_SECURITY_SUPPORT
            value: "true"
          - name: GRPC_XDS_CERT_INSTANCE_OVERRIDE
            value: "true"
          # Enable verbose logging
          # - name: JAVA_OPTS
          #   value: "-Djava.util.logging.config.file=./logging-debug.properties"
        volumeMounts:
          - mountPath: /tmp/grpc-xds/
            name: grpc-td-conf
            readOnly: true
          - mountPath: /var/run/gke-spiffe/certs
            name: gke-spiffe-certs-volume
            readOnly: true
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
      initContainers:
        - name: grpc-td-init
          image: ${td_bootstrap_image}
          imagePullPolicy: Always
          args:
            - "--output=/tmp/bootstrap/td-grpc-bootstrap.json"
            - "--vpc-network-name=${network_name}"
            - "--include-psm-security"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
            - mountPath: /tmp/bootstrap/
              name: grpc-td-conf
        - name: bootstrap-hack
          image: alpine:latest
          imagePullPolicy: Always
          command:
            - "sed"
            - "-i"
            - 's/${network_name}"/${network_name}",\n      "version": "production"/'
            - "/tmp/grpc-xds/td-grpc-bootstrap.json"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
            - mountPath: /tmp/grpc-xds/
              name: grpc-td-conf
      volumes:
        - name: grpc-td-conf
          emptyDir:
            medium: Memory
        - name: gke-spiffe-certs-volume
          csi:
            driver: certs.spiffe.gke.io
