apiVersion: apps/v1
kind: Deployment
metadata:
  name: psm-grpc-client
  labels:
    app: psm-grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psm-grpc-client
  template:
    metadata:
      labels:
        app: psm-grpc-client
    spec:
      serviceAccountName: psm-grpc-client
      containers:
      - name: psm-grpc-client
        image: gcr.io/grpc-testing/xds-gke-interop-client-java-sergii-test:latest
        imagePullPolicy: Always
        args:
            - "--server=xds:///sergii-psm-test-xds-host:8000"
            - "--stats_port=8079"
            - "--qps=1"
            - "--rpc=UnaryCall"
            - "--print_response=true"
        ports:
          - containerPort: 8079
        env:
          - name: GRPC_XDS_BOOTSTRAP
            value: "/tmp/grpc-xds/td-grpc-bootstrap.json"
        volumeMounts:
          - mountPath: /tmp/grpc-xds/
            name: grpc-td-conf
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
      initContainers:
        - name: grpc-td-init
          image: gcr.io/trafficdirector-prod/td-grpc-bootstrap:0.9.0
          imagePullPolicy: IfNotPresent
          args:
            - --output
            - "/tmp/bootstrap/td-grpc-bootstrap.json"
            - --vpc-network-name
            - default-vpc
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
            - mountPath: /tmp/bootstrap/
              name: grpc-td-conf
      volumes:
        - name: grpc-td-conf
          emptyDir:
            medium: Memory
