apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${deployment_name}
  namespace: ${namespace}
  labels:
    app: ${deployment_name}
spec:
  replicas: ${replica_count}
  selector:
    matchLabels:
      app: ${deployment_name}
  template:
    metadata:
      labels:
        app: ${deployment_name}
    spec:
      serviceAccountName: ${deployment_name}
      containers:
      - name: ${deployment_name}
        image: gcr.io/grpc-testing/xds-gke-interop-server-java-sergii-test:latest
        imagePullPolicy: Always
        args:
          - "--port=${test_port}"
        ports:
          - containerPort: ${test_port}
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
