apiVersion: v1
kind: Service
metadata:
  name: ${service_name}
  namespace: ${namespace}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"${port}":{"name":"interop-test-psm-sec1-us-central1-grpc-test-server-java"}}}'
spec:
  type: ClusterIP
  selector:
    app: ${deployment_name}
  ports:
  - port: ${port}
    protocol: TCP
    targetPort: ${port}
