apiVersion: v1
kind: Service
metadata:
  name: psm-grpc-server-service
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name":"interop-test-psm-sec1-us-central1-grpc-test-server-java"}}}'
spec:
  type: ClusterIP
  selector:
    app: psm-grpc-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: psm-grpc-server
  labels:
    app: psm-grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: psm-grpc-server
  template:
    metadata:
      labels:
        app: psm-grpc-server
    spec:
      serviceAccountName: psm-grpc-client
      containers:
      - name: psm-grpc-server
        image: gcr.io/grpc-testing/xds-gke-interop-server-java-sergii-test:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
