name: PSM Interop

on:
  push:
    branches:
    - psm-interop-gh-action-test
  pull_request:

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tools/run_tests/xds_k8s_test_driver'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'tools/run_tests/xds_k8s_test_driver/requirements.lock'

    - name: "Install requirements"
      run: |
        pip list
        pip install -r requirements.lock
        pip list

    - name: "Generate protos"
      run: >
        python -m grpc_tools.protoc --proto_path=../../../
        --python_out=. --grpc_python_out=.
        src/proto/grpc/testing/empty.proto
        src/proto/grpc/testing/messages.proto
        src/proto/grpc/testing/test.proto

    - name: "Run unit tests"
      run: python -m tests.unit
